version: '3'

services:

  redis:
    container_name: redis
    image: redis:7.0.5
    restart: on-failure
    ports:
      - "6380:6379"
    volumes:
      - ./redis-data:/data
    entrypoint: redis-server --appendonly yes

  fetch1:
    container_name: fetch1
    image: cryptoexchange.aggregator.fetch:0.0.1
#    build:
#      context: ./fetch
#      dockerfile: Dockerfile

  #run ver 0.0.2 in parallel
  fetch2:
    container_name: fetch2
    image: cryptoexchange.aggregator.fetch:0.0.2
    build:
      context: ./fetch
      dockerfile: Dockerfile

  api1:
    container_name: api1
    image: cryptoexchange.aggregator.api:0.0.1
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"